account/urls.py
from django.urls import path


from . import views
from .forms import UserEditForm

app_name = 'account'
urlpatterns = [
    path('', views.index, name='index'),
    path('edit/', views.EditView.as_view(), name='edit'),
    path('password/', views.PasswordView.as_view(), name='password'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import UserLoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=UserLoginForm), name='login'),
]

download/urls.py
from django.urls import path

from . import views

app_name = 'download'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('download/', views.DownloadView.as_view(), name='download'),
]

moosify/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('download/', include('download.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

download/models.py
from django.db import models
from django.contrib.auth.models import User

class Track(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    spotify_url = models.URLField()
    filename = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    downloaded = models.BooleanField(default=False)

account/forms.py
from django.contrib.auth.models import User
from django.forms import TextInput, PasswordInput, CharField, HiddenInput
from django.contrib.auth.forms import UserChangeForm, UsernameField, PasswordChangeForm

class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
    
    username = UsernameField(widget=TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username'
    }), label='Username')
    
    email = CharField(widget=TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email'
    }), label='Email')
    
    password = None
    
class PasswordEditForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
    
    old_password = CharField(widget=PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Old password'
    }), label='Old Password')
    
    new_password1 = CharField(widget=PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'New password'
    }), label='New Password')
    
    new_password2 = CharField(widget=PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm new password'
    }), label='Confirm New Password')

core/forms.py
from django.contrib.auth.models import User
from django.forms import TextInput, PasswordInput, CharField
from django.contrib.auth.forms import AuthenticationForm, UsernameField

class UserLoginForm(AuthenticationForm):
    
    username = UsernameField(widget=TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username'
    }))
    
    password = CharField(widget=PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password'
    }))

account/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.core.handlers.wsgi import WSGIRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .forms import UserEditForm, PasswordEditForm

@login_required
def index(request: WSGIRequest):
    return render(request, 'account/index.html')

class EditView(LoginRequiredMixin, View):
    
    def get(self, request: WSGIRequest):
        
        context = {
            'form': UserEditForm(instance=request.user)
        }
        
        return render(request, 'account/edit.html', context)
    
    def post(self, request: WSGIRequest):
    
        form = UserEditForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            return redirect('account:index')
        else:
            return redirect('account:edit')

class PasswordView(LoginRequiredMixin, View):
    
    def get(self, request: WSGIRequest):
        
        context = {
            'form': PasswordEditForm(user=request.user)
        }
        
        return render(request, 'account/password.html', context)
    
    def post(self, request: WSGIRequest):
    
        form = PasswordEditForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('account:index')
        else:
            return redirect('account:password')

core/views.py
from django.views import View
from django.shortcuts import render
from django.core.handlers.wsgi import WSGIRequest

def index(request: WSGIRequest):
    return render(request, 'core/index.html')

class RequestView(View):
    def get(self, request: WSGIRequest):
        return render(request, 'core/request.html')

download/views.py
from os import remove

from moosify.settings import MEDIA_ROOT

from django.http import FileResponse
from django.views.generic import View
from django.shortcuts import render, redirect
from django.core.handlers.wsgi import WSGIRequest
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Track
from .functions import download_track, lookup_track, lookup


def get_history(request: WSGIRequest):
    track_objs = Track.objects.filter(user=request.user).order_by('-timestamp')
    tracks = [(track, lookup_track(track.spotify_url)) for track in track_objs]
    return tracks


class IndexView(LoginRequiredMixin, View):
    template_name = 'download/index.html'

    def get(self, request: WSGIRequest):

        tracks = get_history(request)

        for track in tracks:
            if track[0].downloaded:
                remove(str(MEDIA_ROOT / track[0].filename))
                track[0].delete()
                tracks.pop(tracks.index(track))

        context = {
            'tracks': tracks
        }

        return render(request, IndexView.template_name, context)


class DownloadView(LoginRequiredMixin, View):
    
    def save_track(self, request: WSGIRequest, url: str):
        track = Track.objects.filter(user=request.user, spotify_url__icontains=url).first()
                
        if not track:
            track_meta = download_track(url)
            track = Track(user=request.user, spotify_url=url, filename = str(track_meta) + '.mp3')
            track.save()
            return redirect('download:index')
        else:
            track.downloaded = True
            track.save()
            return FileResponse(open(str(MEDIA_ROOT / track.filename), 'rb'), as_attachment=True)
    
    def get(self, request: WSGIRequest):
        
        url = request.GET.get('url')
        if url and url.startswith('https://open.spotify.com/'):
            if url.startswith('https://open.spotify.com/track/'):
                return self.save_track(request, url)
            
            elif url.startswith('https://open.spotify.com/playlist/') or url.startswith('https://open.spotify.com/album/'):
                playlist = lookup(url)
                if len(playlist) > 9:
                    return render(request, 'download/error.html', {'error': 'Playlist/Album is too large!'})
                for result in playlist:
                    self.save_track(request, result.url)
                return redirect('download:index')
            else:
                return render(request, 'download/error.html', {'error': 'Invalid URL'})
                    
        else:
            return render(request, 'download/error.html', {'error': 'Invalid URL'})

core/templates/core/index.html
{% extends 'base.html' %}

{% block stylesheets %}
  {% load static %}
  <link rel="stylesheet" type='text/css' href="{% static 'css/core/index.css' %}">
{% endblock %}

{% block title %}
  Home
{% endblock %}

{% block content %}
<div class='content'>
  <h1 class='title'>Welcome to <strong>Moosify!</strong></h1>
  <p class='description'>Right now, Moosify is in closed Beta, and access is given by the developer alone. If you were given an account, proceed to <a href="{% url 'core:login' %}">login</a> or request an account by DMing @echoing.void on discord.</p>
</div>
{% endblock %}

core/templates/core/login.html
{% extends "base.html" %}

{% block stylesheets %}
  {% load static %}
  <link rel="stylesheet" type='text/css' href="{% static 'css/core/login.css' %}">
{% endblock stylesheets %}

{% block title %}
  Login
{% endblock title %}

{% block content %}
  <div class='content'>
    <h2 class='header'>Login</h2>
    <form method="post" action="." id='login-form'>
      {% csrf_token %}
      <div>
        <label for="username">Username</label>
        {{ form.username }}
      </div>
      <div>
        <label for="password">Password</label>
        {{ form.password }}
      </div>
      <button type="submit">Login</button>
      {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </form>
  </div>
{% endblock content %}

download/templates/download/error.html
{% extends 'base.html' %}

{% block stylesheets %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/download/index.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock stylesheets %}

{% block title %}
  Download
{% endblock %}

{% block content %}
  <div class='content'>
    <h1 class='title'>An Error Occurred!</h1>
    <p>{{ error }}</p>
    <a href="{% url 'download:index' %}">Back</a>
  </div>
{% endblock %}

download/templates/download/index.html
{% extends 'base.html' %}

{% block stylesheets %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/download/index.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock stylesheets %}

{% block title %}
  Download
{% endblock %}

{% block content %}
  <div class='content'>
    <h1 class='title'>Download tracks</h1>
    <form action="{% url 'download:download' %}" method="get" id='download-form'>
      <input type="text" name="url" placeholder="Paste Spotify link..." id='download' />
      <button type="submit" value="" id='download-submit' class='fa-solid fa-download'></button>
    </form>
    
    <h2 class='header'>Downloads</h2>
    
    <div class='tracks'>
      {% for track in tracks %}
      <div class='song'>
        <img src="{{ track.1.cover_art_url }}" style="width: 150px;" class='cover-art' />
        <h3><a href="{{ track.0.spotify_url }}" target="_blank">{{ track.1 }}</a></h3>
        <form action="{% url 'download:download' %}">
          <input type="hidden" name="url" value="{{ track.1.url }}" />
          <button type="submit" class='fa-solid fa-download track-download'>&nbsp;Download</button>
        </form>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}- Moosify
    </title>
    <link rel='stylesheet' type='text/css' href="{% static 'css/reset.css' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'css/base.css' %}">
    {% block stylesheets %}
    
    {% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <h2 class='logo'>Moosify</h2>
        <a href="{% url 'core:index' %}">Home</a>
        {% if request.user.is_authenticated %}
          <a href="{% url 'download:index' %}">Download</a>
          <a href="{% url 'account:index' %}">Account</a>
          <form action="{% url 'core:logout' %}" method="post">
            {% csrf_token %}
            <button class='btn-danger' type="submit">Logout</button>
          </form>
        {% else %}
          <a href="{% url 'core:login' %}">Login</a>
        {% endif %}
      </nav>
    </header>

    <main>
      {% block content %}

      {% endblock %}
    </main>

    <footer>
      {% if request.user.is_authenticated %}
        <p>Logged in as: {{ request.user.username }}</p>
      {% else %}
        <p>Developed by: Hamza Khattab</p>
      {% endif %}
      <img id='moose' src="{% static 'assets/moose.png' %}">
    </footer>
  </body>
</html>